# Generated by Django 5.2.12 on 2026-03-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pothole_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='confidence',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
