# Generated by Django 5.2.12 on 2026-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pothole_detection', '0002_pothole_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
