# Generated by Django 5.2.12 on 2026-03-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='confidence',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('pothole', 'Pothole'), ('lane', 'Lane'), ('signal', 'Signal')], default=0.0, max_length=20),
            preserve_default=False,
        ),
    ]
